# Generated by Django 4.1 on 2024-02-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PICKIEFOOD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateTimeField()),
                ('nationality', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('religon', models.CharField(max_length=200)),
                ('dietary', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('illness', models.CharField(max_length=200)),
                ('allergen', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
