# Generated by Django 4.1 on 2024-02-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PICKIEFOOD', '0003_rename_nationality_infos_nation_alter_infos_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='infos',
            name='aim',
            field=models.CharField(default='', max_length=200),
        ),
    ]
